<?php

namespace Proyecto\SecurityBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserProjectRepository extends EntityRepository
{
    public function buscarUsuario($user) {
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM ProyectoSecurityBundle:UserProject t WHERE t.username = :user");
        $dql->setParameter('user', $user);
        $users = $dql->getResult();
        return $users;
    }
}
