taskShow:
    pattern: /taskShow/{id}
    defaults: { _controller: TareaBundle:Task:show }
        
taskNew:
    pattern: /neuTask
    defaults: { _controller: TareaBundle:Task:registrarTarea }
        
taskEdit:
    pattern: /taskEdit/{id}
    defaults: { _controller: TareaBundle:Task:taskEdit }
    
#task_edit:
#    pattern: /taskEdit/{id}
#    defaults: { _controller: TareaBundle:Task:edit }
    
#task_update:
#    pattern: /taskEdit/{id}
#    defaults: { _controller: TareaBundle:Task:update }
    
taskDelete:
    pattern: /taskDelete/{id}
    defaults: { _controller: TareaBundle:Task:borrar }
    
eliminarTodas:
    pattern: /deleteAlles
    defaults: { _controller: TareaBundle:Task:deleteAlles }
    
taskList:
    pattern: /listTasks
    defaults: { _controller: TareaBundle:Task:index }
    
taskAlle:
    pattern: /alle
    defaults: { _controller: TareaBundle:Task:listAlle }
 
taskHeute:
    pattern: /heute
    defaults: { _controller: TareaBundle:Task:listTasksHeute }
        
taskErledig:
    pattern: /erledig
    defaults: { _controller: TareaBundle:Task:listTasksErledigPage }
   
clientCreate:
    pattern: /neuClient
    defaults: { _controller: TareaBundle:Client:registrarCliente }
    
clientDeaktivieren:
    pattern: /clientDeaktivieren/{id}
    defaults: { _controller: TareaBundle:Client:desactivar }
    
clientAktivieren:
    pattern: /clientAktivieren/{id}
    defaults: { _controller: TareaBundle:Client:activar }
    
clientEdit:
    pattern: /clientEdit/{id}
    defaults: { _controller: TareaBundle:Client:clientEdit }
    
#client_show:
#    pattern: /showClient/{id}
#    defaults: { _controller: TareaBundle:Client:show }
    
clientList:
    pattern: /listClient
    defaults: { _controller: TareaBundle:Client:listClient }
    
tasksClient:
    pattern: /tasksClient/{id}
    defaults: { _controller: TareaBundle:Task:listTasksDadoCliente }
    
buscarTarea:
    pattern: /buscar
    defaults: { _controller: TareaBundle:Task:buscarTarea }   
    
meinTask:
    pattern: /meineAufgaben
    defaults: { _controller: TareaBundle:Task:misTareas }
    
taskVorDreiMon:
    pattern: /vorDreiMonFertig
    defaults: { _controller: TareaBundle:Task:tareasDreiMonFertig }

export:
    pattern: /export
    defaults: { _controller: TareaBundle:Task:export }
    
fertig:
    pattern: /fertig/{id}
    defaults: { _controller: TareaBundle:Task:fertig }