<?php

namespace Proyecto\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
    public function buscarTareaIdClient($idClient) {
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:Task t WHERE t.client = :idClient");
        $dql->setParameters(array(
            'idClient' => $idClient));
        $tasks = $dql->getResult();
        return $tasks;
    }
    
    public function listaClientesDadoUser($idUser){
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:Client t WHERE t.userProject = :user_id AND t.isActive = 1");
        $dql->setParameter('user_id', $idUser);
        $clients = $dql->getResult();
        return $clients;
    }
    
    public function listaTodosClientesActivos(){
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:Client t WHERE t.isActive = 1");
       // $dql->setParameter(array('active' => '1'));
        $clients = $dql->getResult();
        return $clients;
    }
}
