<?php

namespace Proyecto\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentRepository extends EntityRepository
{
    public function buscarDocPorTaskId($idTask) {
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:Document t WHERE t.task = :idTask");
        $dql->setParameters(array(
            'idTask' => $idTask));
        $docs = $dql->getResult();
        return $docs;
    }
}
