<?php

namespace Proyecto\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RolRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolRepository extends EntityRepository
{
    public function getRolAdmin() {
        $dql = $this->getEntityManager()->createQuery("SELECT r FROM TareaBundle:Rol r WHERE r.rol = :rol_name");
        $dql->setParameter('rol_name', 'ROLE_ADMIN');
        $rol = $dql->getResult();
        foreach ($rol as $value) {
            return $value;
        }        
    }
    
    public function getRolUser() {
        $dql = $this->getEntityManager()->createQuery("SELECT r FROM TareaBundle:Rol r WHERE r.rol = :rol_name");
        $dql->setParameter('rol_name', 'ROLE_USER');
        $rol = $dql->getResult();
        foreach ($rol as $value) {
            return $value;
        }        
    }
}
