<?php

namespace Proyecto\TaskBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * User_TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserTaskClientRepository extends EntityRepository
{
    public function buscarTareaSegunId($idTask) {
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:UserTaskClient t WHERE t.task = :idTask");
        $dql->setParameters(array(
            'idTask' => $idTask));
        $tasks = $dql->getResult();
        return $tasks;
    }
    
    public function misTareas($idUser){
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:UserTaskClient t WHERE t.user = :idUser");
        $dql->setParameters(array(
            'idUser' => $idUser));
        $myTasks = $dql->getResult();
        return $myTasks;
    }
    
    public function tareasDadoCliente($idCliente) {
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:UserTaskClient t WHERE t.client = :client_id");
        $dql->setParameter('client_id', $idCliente);
        $tasks = $dql->getResult();
        return $tasks;
    }
    
    public function listaClientesDadoUser($idUser){
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:UserTaskClient t WHERE t.user = :user_id");
        $dql->setParameter('user_id', $idUser);
        $clients = $dql->getResult();
        return $clients;
    }
    
    public function listaTareasDadoUser($idUser){
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:UserTaskClient t WHERE t.user = :user_id");
        $dql->setParameter('user_id', $idUser);
        $tasks = $dql->getResult();
        return $tasks;
    }
    
    public function tareaDadoUserYTarea($idUser, $idTarea){
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:UserTaskClient t WHERE t.user = :user_id AND t.task = :task_id");
        //$dql->setParameter('user_id', $idUser);
        $dql->setParameters(array(
            'user_id' => $idUser,
            'task_id' => $idTarea));
        $tasks = $dql->getResult();
        return $tasks;
    }
    
    public function tareaDadoClientYTarea($idClient, $idTarea){
        $dql = $this->getEntityManager()->createQuery("SELECT t FROM TareaBundle:UserTaskClient t WHERE t.client = :client_id AND t.task = :task_id");
        $dql->setParameters(array(
            'client_id' => $idClient,
            'task_id' => $idTarea));
        $tasks = $dql->getResult();
        return $tasks;
    }
}
